[package]
name = "crypto-zombies-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.crypto-zombies]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.0"
